### ISSUE TITLE
Bumping Leptos from v0.7 to v0.8 was a breaking change

### ISSUE THREAD

**Issue by trueb2** [KiaShakiba/leptoaster#8]
The minor version needed to go from v0.2 to v0.3. 

Builds that have leptos v0.7 now do not build with leptoaster v0.2.

```toml
# workaround by pinning to a version
leptoaster = { version = "=0.2.1", features = ["csr"] }
```

```
error[E0277]: the trait bound `&fn(leptoaster::toaster::ToasterProps) -> impl leptos::into_view::IntoView {leptoaster::Toaster}: ComponentConstructor<_, _>` is not satisfied
   --> src/app.rs:76:5
    |
76  | /     view! {
77  | |         {move || {
78  | |             if is_workshop.get() {
79  | |                 console::log_1(&"Rendering in workshop mode".into());
...   |
94  | |         <Toaster stacked=true />
95  | |     }
    | |_____^ the trait `ComponentConstructor<_, _>` is not implemented for `&fn(leptoaster::toaster::ToasterProps) -> impl leptos::into_view::IntoView {leptoaster::Toaster}`
    |
note: there are multiple different versions of crate `leptos` in the dependency graph
   --> /Users/jwtrueb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/leptos-0.7.5/src/component.rs:62:1
    |
62  | pub trait ComponentConstructor<P, T> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/app.rs:4:5
    |
4   | use leptoaster::*;
    |     ---------- one version of crate `leptos` used here, as a dependency of crate `leptoaster`
5   | use leptos::prelude::*;
    |     ------ one version of crate `leptos` used here, as a direct dependency of the current crate
    |
   ::: /Users/jwtrueb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/leptos-0.8.2/src/form.rs:245:1
    |
245 | pub trait FromFormData
    | ---------------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `component_view`
   --> /Users/jwtrueb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/leptos-0.7.5/src/component.rs:59:37
    |
59  | pub fn component_view<P, T>(f: impl ComponentConstructor<P, T>, props: P) -> T {
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `component_view`
    = note: this error originates in the macro `view` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `fn(leptoaster::toaster::ToasterProps) -> impl leptos::into_view::IntoView {leptoaster::Toaster}: leptos::prelude::Component<_>` is not satisfied
   --> src/app.rs:76:5
    |
76  | /     view! {
77  | |         {move || {
78  | |             if is_workshop.get() {
79  | |                 console::log_1(&"Rendering in workshop mode".into());
...   |
94  | |         <Toaster stacked=true />
95  | |     }
    | |_____^ the trait `leptos::prelude::Component<_>` is not implemented for fn item `fn(leptoaster::toaster::ToasterProps) -> impl leptos::into_view::IntoView {leptoaster::Toaster}`
    |
note: there are multiple different versions of crate `leptos` in the dependency graph
   --> /Users/jwtrueb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/leptos-0.7.5/src/component.rs:5:1
    |
5   | pub trait Component<P> {}
    | ^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/app.rs:4:5
    |
4   | use leptoaster::*;
    |     ---------- one version of crate `leptos` used here, as a dependency of crate `leptoaster`
5   | use leptos::prelude::*;
    |     ------ one version of crate `leptos` used here, as a direct dependency of the current crate
    |
   ::: /Users/jwtrueb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/leptos-0.8.2/src/form.rs:245:1
    |
245 | pub trait FromFormData
    | ---------------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `component_props_builder`
   --> /Users/jwtrueb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/leptos-0.7.5/src/component.rs:54:15
    |
53  | pub fn component_props_builder<P: PropsOrNoPropsBuilder>(
    |        ----------------------- required by a bound in this function
54  |     _f: &impl Component<P>,
    |               ^^^^^^^^^^^^ required by this bound in `component_props_builder`
    = note: this error originates in the macro `view` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `qview-ui` (lib) due to 2 previous errors
```

**Comment by corebreaker** [comment]
I have this problem, too.
The project is dead ?
